# Generated by Django 4.2.5 on 2023-11-26 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_cursos_disponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoConsultaReclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Formulario_consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=8)),
                ('correo', models.EmailField(max_length=254)),
                ('texto_libre', models.TextField()),
                ('checkbox_llamado', models.BooleanField(default=False)),
                ('tipo_consulta_reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tipoconsultareclamo')),
            ],
        ),
    ]
