# Generated by Django 4.2.5 on 2023-12-05 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_persona_tipocursada_delete_cursos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_Personales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.IntegerField()),
                ('fecha_nacimiento', models.DateTimeField(null=True)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.persona')),
            ],
        ),
    ]
