# Generated by Django 4.2.5 on 2023-12-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_datos_personales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_personales',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
