# Generated by Django 4.2.5 on 2023-12-09 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0010_alter_datos_personales_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=50)),
                ('disponible', models.BooleanField(default=True)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.persona')),
                ('id_tipo_cursada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tipocursada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
