# Generated by Django 4.2.5 on 2023-12-10 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptar',
            name='animal',
        ),
        migrations.AddField(
            model_name='adoptar',
            name='id_animal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.animal'),
            preserve_default=False,
        ),
    ]
