# Generated by Django 4.2.5 on 2023-12-10 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_adoptar_animal_adoptar_id_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colegio',
            name='usuario',
        ),
    ]
