# Generated by Django 4.2.5 on 2023-12-10 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_colegio_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('turno', models.CharField(max_length=20)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fechas',
            name='turno',
        ),
        migrations.AddField(
            model_name='fechas',
            name='id_turno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.turno'),
            preserve_default=False,
        ),
    ]
