# Generated by Django 4.2.5 on 2023-12-12 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_adoptar_estado_colegio_estado_confirmados_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_personales',
            name='id_persona',
        ),
        migrations.AddField(
            model_name='persona',
            name='id_datospersonales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.datos_personales'),
        ),
    ]
