# Generated by Django 4.2.5 on 2023-12-12 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_datos_personales_id_persona_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colegio',
            name='rango_fechas',
        ),
        migrations.AddField(
            model_name='colegio',
            name='id_fechas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.fechas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confirmados',
            name='id_fechas',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='myapp.fechas'),
            preserve_default=False,
        ),
    ]
