# Generated by Django 4.2.5 on 2023-12-13 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_colegio_rango_fechas_colegio_id_fechas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='disponible',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='cursos',
            old_name='disponible',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='fechas',
            old_name='disponible',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='tipocursada',
            old_name='disponible',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='disponible',
            new_name='estado',
        ),
    ]
